name: Test1

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9  # Use the desired Python version

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Assuming you have a requirements file

      # Start Flask app
      - name: Start Flask app
        run: |
          nohup python app.py &  # Start your Flask app in the background
        env:
          FLASK_APP: app.py
          FLASK_ENV: development

      # Wait for the Flask app to be ready
      - name: Wait for Flask to start
        run: |
          until curl --silent --fail http://127.0.0.1:5000/hello; do
            echo "Waiting for Flask app to be ready..."
            sleep 5
          done

      # Test the Flask endpoint
      - name: Test the /health endpoint
        run: |
          RESPONSE=$(curl --write-out "%{http_code}" --silent --output /dev/null http://127.0.0.1:5000/hello)
          if [ "$RESPONSE" -eq 200 ]; then
            echo "Test passed!"
          else
            echo "Test failed with response code: $RESPONSE"
            exit 1
          fi
